#!/usr/bin/env bash
echo ""
versionCheck=$(php -r "echo version_compare(phpversion(), '5.3', '<');")
if [[ $versionCheck ]]; then
    echo -e "PHP version does not support coding standards check... skipping."
    exit
fi
output=$(php php-cs-fixer.phar fix -v --no-interaction --dry-run --level=all ./src)
if [[ $output ]]; then
    while read -r line
    do
        echo -e "\e[37;41m$line\e[00m"
    done <<< "$output"
    false
else
    echo -e "\e[30;42mCoding standards are OK\e[0m"
fi
